# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'managed': False, 'verbose_name_plural': 'Players'},
        ),
    ]
