# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20170304_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('ab', models.IntegerField(blank=True, null=True)),
                ('pa', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('singles', models.IntegerField(blank=True, null=True)),
                ('doubles', models.IntegerField(blank=True, null=True)),
                ('triples', models.IntegerField(blank=True, null=True)),
                ('homerun', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('runs_batted_in', models.IntegerField(blank=True, null=True)),
                ('bb', models.IntegerField(blank=True, null=True)),
                ('ibb', models.IntegerField(blank=True, null=True)),
                ('so', models.IntegerField(blank=True, null=True)),
                ('hbp', models.IntegerField(blank=True, null=True)),
                ('sf', models.IntegerField(blank=True, null=True)),
                ('sh', models.IntegerField(blank=True, null=True)),
                ('gdp', models.IntegerField(blank=True, null=True)),
                ('sb', models.IntegerField(blank=True, null=True)),
                ('cs', models.IntegerField(blank=True, null=True)),
                ('avg', models.IntegerField(blank=True, null=True)),
                ('obp', models.IntegerField(blank=True, null=True)),
                ('slg', models.IntegerField(blank=True, null=True)),
                ('woba', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'marcel',
            },
        ),
        migrations.CreateModel(
            name='Regression',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('avg_distance', models.IntegerField(blank=True, null=True)),
                ('k_rate', models.IntegerField(blank=True, null=True)),
                ('bb_rate', models.IntegerField(blank=True, null=True)),
                ('avg_exit_vel', models.IntegerField(blank=True, null=True)),
                ('barrels_per_bbe', models.IntegerField(blank=True, null=True)),
                ('ld_per', models.IntegerField(blank=True, db_column='LD_per', null=True)),
                ('x_woba', models.TextField(blank=True, db_column='x_wOBA', null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'regression',
            },
        ),
    ]
