# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BattedBallData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('babip', models.IntegerField(blank=True, null=True)),
                ('gb_fb', models.IntegerField(blank=True, null=True)),
                ('ld_per', models.IntegerField(blank=True, null=True)),
                ('gb_per', models.IntegerField(blank=True, null=True)),
                ('fb_per', models.IntegerField(blank=True, null=True)),
                ('iffb_per', models.IntegerField(blank=True, null=True)),
                ('hr_fb', models.IntegerField(blank=True, null=True)),
                ('ifh', models.IntegerField(blank=True, null=True)),
                ('ifhper', models.IntegerField(blank=True, null=True)),
                ('buh', models.IntegerField(blank=True, null=True)),
                ('buh_per', models.IntegerField(blank=True, null=True)),
                ('pull_per', models.IntegerField(blank=True, null=True)),
                ('cent_per', models.IntegerField(blank=True, null=True)),
                ('oppo_per', models.IntegerField(blank=True, null=True)),
                ('soft_per', models.IntegerField(blank=True, null=True)),
                ('med_per', models.IntegerField(blank=True, null=True)),
                ('hard_per', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batted_ball_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ispitcher', models.NullBooleanField()),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegularData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('ab', models.IntegerField(blank=True, null=True)),
                ('pa', models.IntegerField(blank=True, null=True)),
                ('h', models.IntegerField(blank=True, null=True)),
                ('singles', models.IntegerField(blank=True, null=True)),
                ('doubles', models.IntegerField(blank=True, null=True)),
                ('triples', models.IntegerField(blank=True, null=True)),
                ('homerun', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('runs_batted_in', models.IntegerField(blank=True, null=True)),
                ('bb', models.IntegerField(blank=True, null=True)),
                ('ibb', models.IntegerField(blank=True, null=True)),
                ('so', models.IntegerField(blank=True, null=True)),
                ('hbp', models.IntegerField(blank=True, null=True)),
                ('sf', models.IntegerField(blank=True, null=True)),
                ('sh', models.IntegerField(blank=True, null=True)),
                ('gdp', models.IntegerField(blank=True, null=True)),
                ('sb', models.IntegerField(blank=True, null=True)),
                ('cs', models.IntegerField(blank=True, null=True)),
                ('avg', models.IntegerField(blank=True, null=True)),
                ('shift', models.NullBooleanField()),
                ('noshift', models.NullBooleanField()),
                ('trad_shift', models.NullBooleanField()),
                ('nontrad_shift', models.NullBooleanField()),
            ],
            options={
                'db_table': 'regular_data',
                'managed': False,
            },
        ),
    ]
